### ISSUE TITLE
Script for evluating trained model on test set 

### ISSUE THREAD

**Issue by Huzaifg** [ml-jku/UPT#3]
Hi! 

I am unable to find the script that loads a trained model and evaluates it on the test set. Is this not available in the repo yet?

**Comment by BenediktAlkin** [comment]
Hi,

For the lagrangian/RANS experiments the metrics are calculated after every epoch, so there is no explicit script to evaluate a model after it was trained. You can however easily do this by adjusting the yaml to set epoch=0 and add an initializer to each model part where you define from where the model should be loaded (akin to the templates for evaluating trained models for the transient flow experiments which can be found [here](https://github.com/ml-jku/UPT/tree/main/src/yamls/eval/cfd)).

For evaluating transient flow models, there is the [eval_cfd.py](https://github.com/ml-jku/UPT/blob/main/src/eval_cfd.py) which you can call with `python eval_cfd.py --stage_id STAGE_ID --mode MODE` where STAGE_ID is the id from your training run and MODE is either "loss" for evaluating testloss (next-step prediction) or "correlation" to evaluate the correlation time for a full rollout. The `eval_cfd.py` script creates a yaml from [templates](https://github.com/ml-jku/UPT/tree/main/src/yamls/eval/cfd) by fetching the parameters that are set to ??? in the template from the wandb run of the training run. You can then run the evaluation yaml like all other yamls with `python main_train.py --devices 0 --hp yamls_run/EVAL_YAML.yaml`.

**Comment by Huzaifg** [comment]
I see okay. I followed a different approach since I wanted to also export the prediction from the UPT to a vtk file to visualize. I basically used the callbacks to write a [script](https://github.com/Huzaifg/UPT/blob/main/src/eval_lagrangian.py) myself and I think it works fine. 
Thanks for all the help!
