### ISSUE TITLE
Learning simulations of particle-based interaction with rigid bodies with UPT

### ISSUE THREAD

**Issue by Huzaifg** [ml-jku/UPT#4]
Hello!

I would like to model granular flow interacting with baffles (see image below)
![image](https://github.com/ml-jku/UPT/assets/64803446/d33b3ae9-c1e6-48b2-8884-fd3b82946490)

The picture here is modeled using a modification of SPH for granular terrain. The particles are given an initial velocity of 2 m/s in the x direction (towards the baffles). I am fairly certain that this can be modeled using UPT, however I am confused as to how the Baffle's (which are rigid bodies modeled here using Boundary SPH particles) can be included. This use case seems to be similar to section 4.2 and figure 4 in the paper, but I am unable to find more information about how the obstacles were modeled. It would be great if you could point me to code or provide me with some information of how you modeled the rigid bodies in the flow path? My initial thoughts are to add a feature for the particle type and adding a loss for the infringement of a "fluid" particle type with a "rigid body" particle type.

**Comment by BenediktAlkin** [comment]
Hi,

I don't have a definitive answer for this as we haven't investigated lagrangian simulations with obstacles yet.
For the steady state flow simulations in Section 4.2, its simple to model the obstacles as its an eulerian simulation (i.e. the position of the mesh cells doesnt change). For these simulations, the obstacles are simply modeled by never giving the model an input position that lies within an obstacle and never query a position within an obstacle. The orange circles from Figure 4 are overlays and never explicitly passed to the model (only implicitly as the model never gets a position within the obstacle).

Modeling the obstacles as "rigid body" particles with an infringment loss sounds reasonable to me, but as I said, we haven't investigated this particular setting yet.

**Comment by Huzaifg** [comment]
Hello, 

That makes sense. Thanks for letting me know!
